allowBuilds:
  "@parcel/watcher": true
  electron: true
  esbuild: true
blockExoticSubdeps: false
nodeLinker: hoisted
minimumReleaseAgeExclude:
  - "@nkzw/*"
onlyBuiltDependencies:
  - "@nkzw/mdx-editor"
  - "@parcel/watcher"
  - electron
  - esbuild
